services:
  tracy-next:
    image: tracy/next
    container_name: tracy_next
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
      pull: true
    restart: unless-stopped
    ports:
      - "3001:3001"
